#spring.application.name=springstudents
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/student_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
#      ddl-auto: create  1
#      ddl-auto: create-drop 2
#      ddl-auto: create     # 3
      ddl-auto: update     # 4
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true